### ISSUE TITLE
Issue on new portal home-page when extension is running

### ISSUE THREAD

**Issue by erictaur** [seanwu1105/ncu-helper#2]
When the extension is in effect, I have to scroll down a full page to reach portal links and tabs. See uploaded images for full details.

![image](https://user-images.githubusercontent.com/28499265/81101295-83321d80-8f40-11ea-9e09-f14db6106ad0.png)

![image](https://user-images.githubusercontent.com/28499265/81101336-8decb280-8f40-11ea-8659-5eb43efe3484.png)

**Comment by seanwu1105** [comment]
Hello,

Because I have graduated from school, I can no longer access most of the web pages in the NCU portal. Thus, it is hard to test the extension. If you could create a pull request solving this issue, I would happily merge it. As far as I know, all you need to do is to modify the [portal.css](https://github.com/seanwu1105/ncu-helper/blob/master/public/stylesheets/portal.css) file. Simply removing [the iframe height properties](https://github.com/seanwu1105/ncu-helper/blob/200d09e3034ae185f3da123dbb1931f863a614ff/public/stylesheets/portal.css#L16) seems to work, but I am not sure if this change will affect the appearance of other portal pages.
